language: objective-c
osx_image: xcode7.3
xcode_project: applozicdemo.xcodeproj
xcode_scheme: applozicdemo

#install: 
#         - travis_wait mvn install
#bundler_args: --retry 3         
#before_install:
#  - sudo apt-get update
#   -chmod +x travis/before_script.sh
#before_script: travis/before_script.sh
#script: travis/script.sh
before_script: xcodebuild -project ~/build/Applozic/Applozic-iOS-SDK/sample-with-framework/applozicdemo.xcodeproj -scheme applozicdemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 
script: travis_wait 30 scan

#script: pwd 
#notifications:
 # email:
  #  recipients:
    

